# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box.
  # You can search for boxes at https://atlas.hashicorp.com/search.

  config.vm.define 'training.ansible.inventory' do |host|

    host.vm.box = 'ubuntu/trusty64'
    host.vm.box_check_update = false

    config.vm.provider 'virtualbox' do |vb|
      vb.cpus = 2
      vb.memory = 1024
    end
  end
end
